# Generated by Django 2.0.3 on 2018-03-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=20, null=True, verbose_name='Cep Telefonu'),
        ),
    ]
