# Generated by Django 2.0.3 on 2018-03-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180318_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themachinegain',
            name='date',
            field=models.DateTimeField(verbose_name='Zaman'),
        ),
        migrations.AlterField(
            model_name='user_machine',
            name='machine_dead',
            field=models.DateTimeField(verbose_name='Makine Ölüm Zamanı'),
        ),
        migrations.AlterField(
            model_name='user_machine_log',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
