# Generated by Django 2.0.3 on 2018-03-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_user_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tc_no',
            field=models.CharField(max_length=11, null=True, verbose_name='T.C Kimlik Numarası'),
        ),
    ]
