# Generated by Django 2.0.3 on 2018-03-18 02:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180318_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=120, verbose_name='İsim')),
                ('bankname', models.CharField(max_length=60, verbose_name='Banka Adı')),
                ('iban', models.CharField(max_length=40, verbose_name='İban No')),
                ('amount', models.CharField(max_length=50, verbose_name='Tutar')),
                ('cellphone', models.CharField(max_length=20, verbose_name='Telefon Numarası')),
                ('user', models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
