# Generated by Django 2.0.3 on 2018-03-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180313_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tc_no',
            field=models.CharField(default='00000000000', max_length=11, verbose_name='T.C Kimlik Numarası'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(default='(000) 000 00 00', max_length=20, verbose_name='Cep Telefonu'),
        ),
    ]
