# Generated by Django 2.0.3 on 2018-03-18 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Bildirim Gönderim Zamanı'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.CharField(blank=True, max_length=50, verbose_name='Tutar'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bankname',
            field=models.CharField(blank=True, max_length=60, verbose_name='Banka Adı'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cellphone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon Numarası'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='fullname',
            field=models.CharField(blank=True, max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='iban',
            field=models.CharField(blank=True, max_length=40, verbose_name='İban No'),
        ),
    ]
