# Generated by Django 2.0.3 on 2018-03-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180313_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='machine', verbose_name='Görsel')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('properties', models.TextField(verbose_name='Özellikler')),
                ('fiyat', models.FloatField(verbose_name='Fiyat')),
                ('miner_power', models.FloatField(verbose_name='Kazım Gücü')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='users', verbose_name='Profil Fotoğrafı'),
        ),
    ]
