# Generated by Django 2.0.3 on 2018-03-18 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180318_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_machine_log',
            name='payment',
            field=models.BooleanField(default=False, verbose_name='Ödeme Yapıldımı'),
        ),
    ]
