# Generated by Django 2.0.3 on 2018-03-18 03:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_user_machine_log_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_machine_log',
            name='machine',
        ),
        migrations.AddField(
            model_name='user_machine_log',
            name='machine_dead',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Makina Ölüm Zamanı'),
        ),
        migrations.AddField(
            model_name='user_machine_log',
            name='user_machine',
            field=models.ForeignKey(default=1, on_delete=False, to='app.user_machine'),
            preserve_default=False,
        ),
    ]
