# Generated by Django 2.0.3 on 2018-03-18 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_user_machine_log_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themachinegain',
            name='date',
            field=models.DateField(verbose_name='Zaman'),
        ),
    ]
