# Generated by Django 2.0.3 on 2018-03-15 09:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180315_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_machine',
            name='machine',
            field=models.ForeignKey(on_delete=False, to='app.machine'),
        ),
        migrations.AlterField(
            model_name='user_machine',
            name='user',
            field=models.ForeignKey(on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
