# Generated by Django 2.0.3 on 2018-03-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180315_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.CharField(max_length=400, verbose_name='Kısa Yazı')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Zaman')),
            ],
        ),
    ]
