# Generated by Django 2.0.3 on 2018-03-16 12:17

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20180315_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='properties',
            field=ckeditor.fields.RichTextField(verbose_name='Özellikler'),
        ),
        migrations.AlterField(
            model_name='user_machine',
            name='machine',
            field=models.ForeignKey(on_delete=False, to='app.machine', verbose_name='Makina Modeli'),
        ),
        migrations.AlterField(
            model_name='user_machine',
            name='user',
            field=models.ForeignKey(on_delete=False, related_name='usermachine', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
