# Generated by Django 2.0.3 on 2018-03-16 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180316_1517'),
        ('app', '0011_news'),
    ]

    operations = [
    ]
