# Generated by Django 2.0.3 on 2018-03-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_machine_miner_power_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_machine',
            name='miner_power_rate',
            field=models.CharField(choices=[('TH', 'TH/s'), ('GH', 'GH/s'), ('MH', 'MH/s')], default='TH', max_length=10, verbose_name='Kazım Güç Türü'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='machine',
            name='miner_power_rate',
            field=models.CharField(choices=[('TH', 'TH/s'), ('GH', 'GH/s'), ('MH', 'MH/s')], max_length=10, verbose_name='Kazım Güç Türü'),
        ),
    ]
